services:
  lules-denuncias:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/lules-denuncias-db?schema=public
      - POSTGRES_HOST=postgres # Nueva variable de entorno
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lules-denuncias-db
    volumes:
      - lules-denuncias-db:/var/lib/postgresql/data

volumes:
  lules-denuncias-db:
    external: true