version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres-lules-denuncias-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: lules-denuncias-db
    ports:
      - "5433:5432"
