services:
  postgres:
    image: postgres
    container_name: ${POSTGRES_DB}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-lules-denuncias:/var/lib/postgresql/data
    
volumes:
  db-lules-denuncias:
    external: true